theme: jekyll-theme-architect


# Name of your site (displayed in the header)
title: Coded Poetry

# Short bio or description (displayed in the header)
description: Software is a Metaphore

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: fllaca
