# Site settings
name: Coded Poetry
title: and other technical thoughts...
description: and other technical thoughts...
#baseurl: "/will-jekyll-template" # the subpath of your site, e.g. /blog
url: "http://localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Fernando Llaca
user_description: Code and Poetry enthusiast
user_title: Poetry Developer 
email: ferllarom@gmail.com
twitter_username: NandoLlaca
github_username:  fllaca
gplus_username:  fllaca
disqus_username: fllaca

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
